# Generated by Django 5.2.9 on 2026-01-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_alter_module_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
