# Generated by Django 5.2.9 on 2026-01-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_module_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodule',
            options={'ordering': ['user', 'sequence', 'module__code'], 'verbose_name': 'User Module', 'verbose_name_plural': 'User Modules'},
        ),
        migrations.AddField(
            model_name='usermodule',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Indicates if this is the default module for the user', verbose_name='Is Default Module'),
        ),
        migrations.AddField(
            model_name='usermodule',
            name='sequence',
            field=models.IntegerField(default=0, help_text='Order in which modules are displayed (lower numbers first)', verbose_name='Display Sequence'),
        ),
    ]
