# Generated by Django 5.2.9 on 2026-01-26 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_alter_usermodule_options_usermodule_is_default_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodule',
            options={'verbose_name': 'User Module', 'verbose_name_plural': 'User Modules'},
        ),
    ]
