# Generated by Django 3.2.25 on 2026-09-10 08:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0007_auto_20260910_1328'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSubscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('billing_cycle', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Monthly', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled'), ('Suspended', 'Suspended'), ('Trial', 'Trial')], default='Pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded'), ('Processing', 'Processing')], default='Pending', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('trial_end_date', models.DateField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('next_billing_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('auto_renew', models.BooleanField(default=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('minutes_used', models.DecimalField(decimal_places=4, default=0, help_text='Fractional minutes consumed this billing period', max_digits=12)),
                ('ai_tokens_used', models.BigIntegerField(default=0, help_text='AI tokens consumed this billing period')),
                ('embeddings_used', models.BigIntegerField(default=0, help_text='Embeddings consumed this billing period (not refunded on document delete)')),
                ('usage_period_start', models.DateField(blank=True, help_text='Start of current usage billing window', null=True)),
                ('emergency_grace_ends_at', models.DateTimeField(blank=True, help_text='Client-only emergency 24hr grace access expiry', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Subscription',
                'verbose_name_plural': 'Client Subscriptions',
                'db_table': 'client_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('tier', models.CharField(choices=[('Basic', 'Basic'), ('Pro', 'Pro'), ('Enterprise', 'Enterprise'), ('Custom', 'Custom')], default='Basic', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (0 to 100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('user_limit', models.PositiveIntegerField(default=10, help_text='Maximum number of users')),
                ('api_calls_per_month', models.PositiveIntegerField(default=50000, help_text='API calls per month')),
                ('minutes_per_month', models.PositiveIntegerField(default=2000, help_text='Minutes per month')),
                ('ai_tokens_per_month', models.PositiveIntegerField(default=1000000, help_text='AI tokens per month')),
                ('embeddings_per_month', models.PositiveIntegerField(default=20000, help_text='Embeddings limit per month (document upload indexing)')),
                ('ai_agents_count', models.PositiveIntegerField(default=1, help_text='Number of AI Agents included')),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False, verbose_name='Mark as Popular Plan')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order in which plans are displayed')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Tax rate in percentage', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'db_table': 'subscription_plans',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Subscription Type',
                'verbose_name_plural': 'Subscription Types',
                'db_table': 'subscription_types',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Paid', 'Paid'), ('Overdue', 'Overdue'), ('Void', 'Void')], default='Draft', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/pdfs/')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('overdue_alert_sent', models.BooleanField(default=False)),
                ('overdue_alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(db_column='subscription_id', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='subscription.clientsubscription')),
            ],
            options={
                'verbose_name': 'Subscription Invoice',
                'verbose_name_plural': 'Subscription Invoices',
                'db_table': 'subscription_invoices',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.AddField(
            model_name='clientsubscription',
            name='plan',
            field=models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.PROTECT, related_name='client_subscriptions', to='subscription.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='clientsubscription',
            name='subscription_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscription.subscriptiontype'),
        ),
        migrations.CreateModel(
            name='SubscriptionPlanModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('parent_id', models.IntegerField(blank=True, default=None, help_text='Optional parent module_id in the client sidebar tree', null=True)),
                ('module', models.ForeignKey(db_column='module_id', on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plans', to='modules.module')),
                ('plan', models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.CASCADE, related_name='plan_modules', to='subscription.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Subscription Plan Module',
                'verbose_name_plural': 'Subscription Plan Modules',
                'db_table': 'subscription_plan_modules',
                'ordering': ['sequence', 'module_id'],
                'unique_together': {('plan', 'module')},
            },
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['tier', 'is_active'], name='subscriptio_tier_8542f6_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['price'], name='subscriptio_price_704aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioninvoice',
            index=models.Index(fields=['invoice_number'], name='subscriptio_invoice_1f5acc_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioninvoice',
            index=models.Index(fields=['status', 'due_date'], name='subscriptio_status_32c05f_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioninvoice',
            index=models.Index(fields=['subscription', 'status'], name='subscriptio_subscri_329d7e_idx'),
        ),
        migrations.AddIndex(
            model_name='clientsubscription',
            index=models.Index(fields=['client', 'status'], name='client_subs_client__ac37ca_idx'),
        ),
        migrations.AddIndex(
            model_name='clientsubscription',
            index=models.Index(fields=['status', 'end_date'], name='client_subs_status_75a76d_idx'),
        ),
        migrations.AddIndex(
            model_name='clientsubscription',
            index=models.Index(fields=['end_date'], name='client_subs_end_dat_f82889_idx'),
        ),
    ]
