# Generated by Django 5.2.9 on 2026-01-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
