# Generated by Django 3.2.25 on 2026-09-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_seed_client_telephony_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodule',
            name='parent_id',
            field=models.IntegerField(blank=True, default=None, help_text="The module_id of the parent module in this user's sidebar tree. NULL means this module is top-level for this user.", null=True, verbose_name='Parent Module ID (per-user)'),
        ),
        migrations.AddField(
            model_name='usermodule',
            name='show_in_sidebar',
            field=models.BooleanField(default=True, help_text='If true, this module appears in the sidebar. If false, it is hidden from sidebar navigation.', verbose_name='Show in Sidebar'),
        ),
    ]
